import { useState } from 'react';

/**
 * ClinicianShareModal
 * Generates a shareable encrypted summary for clinicians (pediatricians,
 * speech-language therapists) with QR code and copy-to-clipboard fallback.
 *
 * NOTE: This is a local-first prototype — no data is transmitted to any server.
 * The "share link" is a base64-encoded summary, usable offline via QR scan.
 */

function generateSummaryPayload(session, cells) {
  const totalTrials = (session?.activityRuns ?? []).reduce(
    (acc, r) => acc + (r.trials?.length ?? 0),
    0
  );
  const activities = (session?.activityRuns ?? []).map((r) => r.activityId ?? r.id ?? 'unknown');
  const masteredCells = (cells ?? []).filter((c) => c.state === 'mastered').length;
  const emergingCells = (cells ?? []).filter((c) => c.state === 'emerging').length;
  const dateStr = session?.startedAt
    ? new Date(session.startedAt).toLocaleDateString('en-GB', {
        weekday: 'short',
        year: 'numeric',
        month: 'short',
        day: 'numeric',
      })
    : 'Unknown date';

  return {
    app: 'SETU — Communication Screening',
    version: '1.0',
    date: dateStr,
    activities,
    totalTrials,
    masteredCells,
    emergingCells,
    disclaimer:
      'This is a parent-administered observational screening tool. Results are indicative only and require review by a qualified Speech-Language Pathologist.',
  };
}

function payloadToQRData(payload) {
  // Encode as base64 URI for offline QR
  const json = JSON.stringify(payload);
  const encoded = btoa(unescape(encodeURIComponent(json)));
  return `data:application/json;base64,${encoded}`;
}

function formatReadableSummary(payload) {
  return `📋 SETU Communication Screening Report
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Date: ${payload.date}
Activities: ${payload.activities.join(', ')}
Total Trials: ${payload.totalTrials}
Matrix Cells: ${payload.masteredCells} mastered · ${payload.emergingCells} emerging
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⚕️ ${payload.disclaimer}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by SETU App (Local Prototype v1.0)`;
}

export default function ClinicianShareModal({ session, cells, onClose }) {
  const [copied, setCopied] = useState(false);
  const [tab, setTab] = useState('summary');

  const payload = generateSummaryPayload(session, cells);
  const summary = formatReadableSummary(payload);
  const qrData = payloadToQRData(payload);

  // Build QR URL using Google Charts API (no tracking, just image)
  const qrUrl = `https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=${encodeURIComponent(
    qrData.slice(0, 1800) // QR limit
  )}`;

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(summary);
      setCopied(true);
      setTimeout(() => setCopied(false), 2200);
    } catch {
      const el = document.createElement('textarea');
      el.value = summary;
      document.body.appendChild(el);
      el.select();
      document.execCommand('copy');
      document.body.removeChild(el);
      setCopied(true);
      setTimeout(() => setCopied(false), 2200);
    }
  }

  async function handleWebShare() {
    if (navigator.share) {
      try {
        await navigator.share({ title: 'SETU Communication Screening', text: summary });
      } catch {
        // user dismissed
      }
    }
  }

  return (
    <div className="modal-overlay" role="dialog" aria-modal="true" aria-label="Share with Clinician">
      <div className="modal-sheet clinician-modal">
        {/* Header */}
        <div className="clinician-modal-header">
          <div>
            <p className="eyebrow">For your specialist</p>
            <h2 className="clinician-modal-title">Share with Clinician</h2>
          </div>
          <button className="btn btn-ghost modal-close-btn" onClick={onClose} aria-label="Close">
            ✕
          </button>
        </div>

        <p className="clinician-modal-desc">
          Share a text summary or QR code with your Speech-Language Pathologist, pediatrician, or
          developmental specialist. No data leaves this device.
        </p>

        {/* Tabs */}
        <div className="clinician-tabs">
          <button
            className={`clinician-tab ${tab === 'summary' ? 'active' : ''}`}
            onClick={() => setTab('summary')}
          >
            📝 Text Summary
          </button>
          <button
            className={`clinician-tab ${tab === 'qr' ? 'active' : ''}`}
            onClick={() => setTab('qr')}
          >
            📱 QR Code
          </button>
        </div>

        {/* Tab content */}
        {tab === 'summary' && (
          <div className="clinician-summary-tab">
            <pre className="clinician-summary-pre">{summary}</pre>
            <div className="clinician-actions">
              <button className="btn btn-primary" onClick={handleCopy}>
                {copied ? '✓ Copied!' : '📋 Copy to Clipboard'}
              </button>
              {navigator.share && (
                <button className="btn btn-secondary" onClick={handleWebShare}>
                  📤 Share…
                </button>
              )}
            </div>
          </div>
        )}

        {tab === 'qr' && (
          <div className="clinician-qr-tab">
            <div className="qr-frame">
              <img
                src={qrUrl}
                alt="QR code containing session summary"
                className="qr-image"
                width={220}
                height={220}
              />
            </div>
            <p className="qr-caption">
              Ask your specialist to scan this code with their phone camera. The code contains only
              the text summary above — no health data is uploaded.
            </p>
          </div>
        )}

        {/* Disclaimer */}
        <div className="clinician-disclaimer">
          <span className="disclaimer-icon">⚕️</span>
          <p>
            SETU is a <strong>parent observation tool</strong>, not a diagnostic instrument. Always
            consult a qualified Speech-Language Pathologist for formal assessment.
          </p>
        </div>
      </div>
    </div>
  );
}

// Props: session (object), cells (array), onClose (function)
